name: Test

on: [push, pull_request]

jobs:
  node-tests:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Build
      run: |
        npm install
        npm run build
    - name: Run tests
      run: npm run test
